spring:
  application:
    name: chaos.monkey

server:
    port: 8081

management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: chaosmonkey,health,info

chaos:
  monkey:
    enabled: true